// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// ArticleTag is the golang structure for table gf_article_tag.
type ArticleTag internal.ArticleTag

// Fill with you ideas below.