// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// Article is the golang structure for table gf_article.
type Article internal.Article

// Fill with you ideas below.