// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// Ask is the golang structure for table gf_ask.
type Ask internal.Ask

// Fill with you ideas below.