// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

const (
	ContextUserKey = "ContextUserKey"
)

// 请求上下文结构
type Context struct {
	UserId       uint   // 用户ID
	UserPassport string // 用户账号
	UserNickname string // 用户名称
}
