// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/net/ghttp"
)

const (
	ContextUserKey = "ContextUserKey"
)

// 请求上下文结构
type Context struct {
	Session *ghttp.Session // 当前Session管理对象
	User    *ContextUser   // 上下文用户信息
	View    *ContextView   // 上下文视图管理对象
	Data    g.Map          // 自定KV变量，业务模块根据需要设置，不固定
}

// 请求上下文中的视图信息
type ContextView struct {
	Layout string // 默认布局模板
	System string // 前台还是后台系统
}

// 请求上下文中的用户信息
type ContextUser struct {
	Id       uint   // 用户ID
	Passport string // 用户账号
	Nickname string // 用户名称
	Avatar   string // 用户头像
}
