// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// ContentTag is the golang structure for table gf_content_tag.
type ContentTag internal.ContentTag

// Fill with you ideas below.