// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

const (
	// 同一用户1分钟之内最大上传数量
	FileMaxUploadCountMinute = 10
)
