// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

const (
	InteractTypeZan           = 0
	InteractTypeCai           = 1
	InteractTargetTypeContent = "content"
	InteractTargetTypeReply   = "reply"
)
