// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// Interact is the golang structure for table gf_interact.
type Interact internal.Interact

const (
	InteractTypeZan           = 0
	InteractTypeCai           = 1
	InteractTargetTypeContent = "content"
	InteractTargetTypeReply   = "reply"
)
