// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// RoleAuth is the golang structure for table gf_role_auth.
type RoleAuth internal.RoleAuth

// Fill with you ideas below.