// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// Setting is the golang structure for table gf_setting.
type Setting internal.Setting
