// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// Tag is the golang structure for table gf_tag.
type Tag internal.Tag

// Fill with you ideas below.