// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// TopicTag is the golang structure for table gf_topic_tag.
type TopicTag internal.TopicTag

// Fill with you ideas below.