// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// Topic is the golang structure for table gf_topic.
type Topic internal.Topic

// Fill with you ideas below.