// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// UserDetail is the golang structure for table gf_user_detail.
type UserDetail internal.UserDetail

// Fill with you ideas below.