// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// UserRoleRoute is the golang structure for table gf_user_role_route.
type UserRoleRoute internal.UserRoleRoute

// Fill with you ideas below.