// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// UserLogin is the golang structure for table gf_user_login.
type UserLogin internal.UserLogin

// Fill with you ideas below.