// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// UserStat is the golang structure for table gf_user_stat.
type UserStat internal.UserStat

// Fill with you ideas below.