// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// UserRoleAuth is the golang structure for table gf_user_role_auth.
type UserRoleAuth internal.UserRoleAuth

// Fill with you ideas below.