// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// User is the golang structure for table gf_user.
type User internal.User

// Fill with you ideas below.