// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// UserAuth is the golang structure for table gf_user_auth.
type UserAuth internal.UserAuth

// Fill with you ideas below.