// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import "github.com/gogf/gf/frame/g"

// 视图渲染内容对象
type View struct {
	Title       string // 页面标题
	Keywords    string // 页面Keywords
	Description string // 页面Description
	MainTpl     string // 自定义MainTpl展示模板文件
	Data        g.Map  // 页面参数
}
