// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"focus/app/model/internal"
)

// ZanCai is the golang structure for table gf_zan_cai.
type ZanCai internal.ZanCai

const (
	ZanCaiTypeZan            = 0
	ZanCaiTypeCai            = 1
	ZanCaiContentTypeContent = "content"
	ZanCaiContentTypeReply   = "reply"
)
