// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Category is the golang structure for table gf_category.
type Category struct {
	Id          uint        `orm:"id,primary"   json:"id"`           // 分类ID，自增主键
	ContentType string      `orm:"content_type" json:"content_type"` // 内容类型：topic, ask, article, reply
	Key         string      `orm:"key"          json:"key"`          // 栏目唯一键名，用于程序部分场景硬编码，一般不会用得到
	ParentId    uint        `orm:"parent_id"    json:"parent_id"`    // 父级分类ID，用于层级管理
	UserId      uint        `orm:"user_id"      json:"user_id"`      // 创建的用户ID
	Name        string      `orm:"name"         json:"name"`         // 分类名称
	Sort        uint        `orm:"sort"         json:"sort"`         // 排序，数值越低越靠前，默认为添加时的时间戳，可用于置顶
	Thumb       string      `orm:"thumb"        json:"thumb"`        // 封面图
	Brief       string      `orm:"brief"        json:"brief"`        // 简述
	Content     string      `orm:"content"      json:"content"`      // 详细介绍
	CreatedAt   *gtime.Time `orm:"created_at"   json:"created_at"`   // 创建时间
	UpdatedAt   *gtime.Time `orm:"updated_at"   json:"updated_at"`   // 修改时间
}
