// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// ContentTag is the golang structure for table gf_content_tag.
type ContentTag struct {
    Id        int         `orm:"id,primary" json:"id"`         //           
    Type      string      `orm:"type"       json:"type"`       // 内容模型  
    TagName   string      `orm:"tag_name"   json:"tag_name"`   // 标签名称  
    CreatedAt *gtime.Time `orm:"created_at" json:"created_at"` // 创建时间  
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updated_at"` // 修改时间  
}