// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Interact is the golang structure for table gf_interact.
type Interact struct {
	Id         uint        `orm:"id,primary"  json:"id"`          // 自增ID
	Type       int         `orm:"type"        json:"type"`        // 操作类型。0:赞，1:踩。
	UserId     uint        `orm:"user_id"     json:"user_id"`     // 操作用户
	TargetId   uint        `orm:"target_id"   json:"target_id"`   // 对应内容ID，该内容可能是content, reply
	TargetType string      `orm:"target_type" json:"target_type"` // 内容模型: content, reply, 具体由程序定义
	Count      uint        `orm:"count"       json:"count"`       // 操作数据值
	CreatedAt  *gtime.Time `orm:"created_at"  json:"created_at"`  //
	UpdatedAt  *gtime.Time `orm:"updated_at"  json:"updated_at"`  //
}
