// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Reply is the golang structure for table gf_reply.
type Reply struct {
    Id          uint        `orm:"id,primary"   json:"id"`           // 回复ID                                   
    ParentId    uint        `orm:"parent_id"    json:"parent_id"`    // 回复对应的上一级回复ID(没有的话默认为0)  
    ContentType string      `orm:"content_type" json:"content_type"` // 评论类型: topic, ask, article, reply     
    TargetId    uint        `orm:"target_id"    json:"target_id"`    // 对应内容ID                               
    UserId      uint        `orm:"user_id"      json:"user_id"`      // 网站用户ID                               
    ZanCount    uint        `orm:"zan_count"    json:"zan_count"`    // 赞                                       
    CaiCount    uint        `orm:"cai_count"    json:"cai_count"`    // 踩                                       
    Title       string      `orm:"title"        json:"title"`        // 回复标题                                 
    Content     string      `orm:"content"      json:"content"`      // 回复内容                                 
    CreatedAt   *gtime.Time `orm:"created_at"   json:"created_at"`   // 创建时间                                 
    UpdatedAt   *gtime.Time `orm:"updated_at"   json:"updated_at"`   //                                          
}