// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// RoleAuth is the golang structure for table gf_role_auth.
type RoleAuth struct {
    Id        uint        `orm:"id,primary" json:"id"`         // 自增ID    
    RoleId    uint        `orm:"role_id"    json:"role_id"`    // 角色ID    
    AuthId    uint        `orm:"auth_id"    json:"auth_id"`    // 权限ID    
    CreatedAt *gtime.Time `orm:"created_at" json:"created_at"` // 创建时间  
}