// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Setting is the golang structure for table gf_setting.
type Setting struct {
	K         string      `orm:"k,primary"  json:"k"`          // 键名
	V         string      `orm:"v"          json:"v"`          // 键值
	CreatedAt *gtime.Time `orm:"created_at" json:"created_at"` // 创建时间
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updated_at"` // 更新时间
}
