// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Tag is the golang structure for table gf_tag.
type Tag struct {
    Name      string      `orm:"name,primary" json:"name"`       // 标签名称      
    Count     uint        `orm:"count"        json:"count"`      // 标签内容数量  
    CreatedAt *gtime.Time `orm:"created_at"   json:"created_at"` //               
    UpdatedAt *gtime.Time `orm:"updated_at"   json:"updated_at"` //               
}