// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// UserRoleAuth is the golang structure for table gf_user_role_auth.
type UserRoleAuth struct {
    Id        uint        `orm:"id,primary" json:"id"`         // 自增ID                                  
    RoleId    uint        `orm:"role_id"    json:"role_id"`    // 角色ID                                  
    Name      string      `orm:"name"       json:"name"`       // 权限名称                                
    Key       string      `orm:"key"        json:"key"`        // 权限键名(用于程序)                      
    Value     string      `orm:"value"      json:"value"`      // 权限键值，部分自定义权限可能有键值存在  
    Brief     string      `orm:"brief"      json:"brief"`      // 自定义权限描述                          
    CreatedAt *gtime.Time `orm:"created_at" json:"created_at"` // 创建时间                                
}