// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table gf_user.
type User struct {
    Id        uint        `orm:"id,primary" json:"id"`         // UID                                                                 
    RoleId    int         `orm:"role_id"    json:"role_id"`    // 角色ID，允许负数：< 0 系统使用; > 0 业务使用. 一个用户只有一个角色  
    Passport  string      `orm:"passport"   json:"passport"`   // 账号                                                                
    Password  string      `orm:"password"   json:"password"`   // MD5密码                                                             
    Nickname  string      `orm:"nickname"   json:"nickname"`   // 昵称                                                                
    Avatar    string      `orm:"avatar"     json:"avatar"`     // 头像地址                                                            
    Status    int         `orm:"status"     json:"status"`     // 状态 0:启用 1:禁用                                                  
    Gender    int         `orm:"gender"     json:"gender"`     // 性别 0: 未设置 1: 男 2: 女                                          
    CreatedAt *gtime.Time `orm:"created_at" json:"created_at"` // 注册时间                                                            
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updated_at"` // 更新时间                                                            
}