// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// UserStat is the golang structure for table gf_user_stat.
type UserStat struct {
    UserId    uint        `orm:"user_id,primary" json:"user_id"`    // 用户ID    
    ZanCount  uint        `orm:"zan_count"       json:"zan_count"`  // 被赞次数  
    CaiCount  uint        `orm:"cai_count"       json:"cai_count"`  // 被踩次数  
    CreatedAt *gtime.Time `orm:"created_at"      json:"created_at"` // 创建时间  
    UpdatedAt *gtime.Time `orm:"updated_at"      json:"updated_at"` // 更新时间  
}