// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// UserLogin is the golang structure for table gf_user_login.
type UserLogin struct {
    Id        uint        `orm:"id,primary" json:"id"`         // 主键ID    
    UserId    uint        `orm:"user_id"    json:"user_id"`    // 用户ID    
    Ip        string      `orm:"ip"         json:"ip"`         // 登录IP    
    Result    string      `orm:"result"     json:"result"`     // 登录结果  
    CreatedAt *gtime.Time `orm:"created_at" json:"created_at"` // 登录时间  
}