// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// UserRoleRoute is the golang structure for table gf_user_role_route.
type UserRoleRoute struct {
    Id        uint        `orm:"id,primary" json:"id"`         // 自增ID                                          
    RoleId    uint        `orm:"role_id"    json:"role_id"`    // 角色ID                                          
    Name      string      `orm:"name"       json:"name"`       // 权限名称                                        
    Method    string      `orm:"method"     json:"method"`     // HTTP Method，可能为ALL/GET/PUT/POST/DELETE等等  
    Route     string      `orm:"route"      json:"route"`      // 路由规则                                        
    Pattern   string      `orm:"pattern"    json:"pattern"`    // 模糊路由规则的正则表达式                        
    Brief     string      `orm:"brief"      json:"brief"`      // 权限描述                                        
    CreatedAt *gtime.Time `orm:"created_at" json:"created_at"` // 创建时间                                        
}