// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"focus/app/dao/internal"
)

// articleDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type articleDao struct {
	*internal.ArticleDao
}

var (
	// Article is globally public accessible object for table {TplTableName} operations.
	Article = &articleDao{
		internal.Article,
	}
)

// Fill with you ideas below.