// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"focus/app/dao/internal"
)

var AskTag = &askTagDao{
	internal.AskTag,
}

// askTagDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type askTagDao struct {
	*internal.AskTagDao
}

// Fill with you ideas below.
