// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"focus/app/dao/internal"
	"focus/app/model"
)

// topicDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type topicDao struct {
	*internal.TopicDao
}

var (
	// Topic is globally public accessible object for table {TplTableName} operations.
	Topic = &topicDao{
		internal.Topic,
	}
)

// 创建
func (d *topicDao) Create(r *model.TopicDaoCreateReq) error {
	_, err := d.Data(r).Save()
	return err
}

// 修改
func (d *topicDao) Update(r *model.TopicDaoUpdateReq) error {
	_, err := d.Data(r).Save()
	return err
}

// 删除
func (d *topicDao) Delete(id uint) error {
	_, err := d.Where(d.Columns.Id, id).Delete()
	return err
}
