// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"focus/app/dao/internal"
)

var TopicTag = &topicTagDao{
	internal.TopicTag,
}

// topicTagDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type topicTagDao struct {
	*internal.TopicTagDao
}

// Fill with you ideas below.
