// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"focus/app/dao/internal"
)

var UserAuth = &userAuthDao{
	internal.UserAuth,
}

// userAuthDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type userAuthDao struct {
	*internal.UserAuthDao
}

// Fill with you ideas below.
