// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package question

import "github.com/gogf/gf/text/gstr"

// 获得问答的标签列表
func (r *Entity) GetTags() []string {
	return gstr.SplitAndTrim(r.Tags, "#")
}

