// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package define

const (
	CaptchaDefaultName = "CaptchaDefaultName"
)
