// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"database/sql"
	"focus/app/model"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
	"time"
)

// TagDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type TagDao struct {
	gmvc.M
	Table   string
	Columns tagColumns
}

// TagColumns defines and stores column names for table gf_tag.
type tagColumns struct {
	Name       string // 标签名称      
    Count      string // 标签内容数量  
    CreatedAt  string //               
    UpdatedAt  string //
}

var (
	// Tag is globally public accessible object for table gf_tag operations.
	Tag = &TagDao{
		M:     g.DB("default").Table("gf_tag").Safe(),
		Table: "gf_tag",
		Columns: tagColumns{
			Name:      "name",        
            Count:     "count",       
            CreatedAt: "created_at",  
            UpdatedAt: "updated_at",
		},
	}
)

// As sets an alias name for current table.
func (dao *TagDao) As(as string) *TagDao {
	return &TagDao{M:dao.M.As(as)}
}

// TX sets the transaction for current operation.
func (dao *TagDao) TX(tx *gdb.TX) *TagDao {
	return &TagDao{M:dao.M.TX(tx)}
}

// Master marks the following operation on master node.
func (dao *TagDao) Master() *TagDao {
	return &TagDao{M:dao.M.Master()}
}

// Slave marks the following operation on slave node.
// Note that it makes sense only if there's any slave node configured.
func (dao *TagDao) Slave() *TagDao {
	return &TagDao{M:dao.M.Slave()}
}

// LeftJoin does "LEFT JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").LeftJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").LeftJoin("user_detail", "ud", "ud.uid=u.uid")
func (dao *TagDao) LeftJoin(table ...string) *TagDao {
	return &TagDao{M:dao.M.LeftJoin(table...)}
}

// RightJoin does "RIGHT JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").RightJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").RightJoin("user_detail", "ud", "ud.uid=u.uid")
func (dao *TagDao) RightJoin(table ...string) *TagDao {
	return &TagDao{M:dao.M.RightJoin(table...)}
}

// InnerJoin does "INNER JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").InnerJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").InnerJoin("user_detail", "ud", "ud.uid=u.uid")
func (dao *TagDao) InnerJoin(table ...string) *TagDao {
	return &TagDao{M:dao.M.InnerJoin(table...)}
}

// Fields sets the operation fields of the model, multiple fields joined using char ','.
func (dao *TagDao) Fields(fields ...string) *TagDao {
	return &TagDao{M:dao.M.Fields(fields...)}
}

// FieldsEx sets the excluded operation fields of the model, multiple fields joined using char ','.
func (dao *TagDao) FieldsEx(fields ...string) *TagDao {
	return &TagDao{M:dao.M.FieldsEx(fields...)}
}

// Option sets the extra operation option for the model.
func (dao *TagDao) Option(option int) *TagDao {
	return &TagDao{M:dao.M.Option(option)}
}

// OmitEmpty sets OPTION_OMITEMPTY option for the model, which automatically filers
// the data and where attributes for empty values.
func (dao *TagDao) OmitEmpty() *TagDao {
	return &TagDao{M:dao.M.OmitEmpty()}
}

// Filter marks filtering the fields which does not exist in the fields of the operated table.
func (dao *TagDao) Filter() *TagDao {
	return &TagDao{M:dao.M.Filter()}
}

// Where sets the condition statement for the model. The parameter <where> can be type of
// string/map/gmap/slice/struct/*struct, etc. Note that, if it's called more than one times,
// multiple conditions will be joined into where statement using "AND".
// Eg:
// Where("uid=10000")
// Where("uid", 10000)
// Where("money>? AND name like ?", 99999, "vip_%")
// Where("uid", 1).Where("name", "john")
// Where("status IN (?)", g.Slice{1,2,3})
// Where("age IN(?,?)", 18, 50)
// Where(User{ Id : 1, UserName : "john"})
func (dao *TagDao) Where(where interface{}, args ...interface{}) *TagDao {
	return &TagDao{M:dao.M.Where(where, args...)}
}

// WherePri does the same logic as M.Where except that if the parameter <where>
// is a single condition like int/string/float/slice, it treats the condition as the primary
// key value. That is, if primary key is "id" and given <where> parameter as "123", the
// WherePri function treats the condition as "id=123", but M.Where treats the condition
// as string "123".
func (dao *TagDao) WherePri(where interface{}, args ...interface{}) *TagDao {
	return &TagDao{M:dao.M.WherePri(where, args...)}
}

// And adds "AND" condition to the where statement.
func (dao *TagDao) And(where interface{}, args ...interface{}) *TagDao {
	return &TagDao{M:dao.M.And(where, args...)}
}

// Or adds "OR" condition to the where statement.
func (dao *TagDao) Or(where interface{}, args ...interface{}) *TagDao {
	return &TagDao{M:dao.M.Or(where, args...)}
}

// Group sets the "GROUP BY" statement for the model.
func (dao *TagDao) Group(groupBy string) *TagDao {
	return &TagDao{M:dao.M.Group(groupBy)}
}

// Order sets the "ORDER BY" statement for the model.
func (dao *TagDao) Order(orderBy ...string) *TagDao {
	return &TagDao{M:dao.M.Order(orderBy...)}
}

// Limit sets the "LIMIT" statement for the model.
// The parameter <limit> can be either one or two number, if passed two number is passed,
// it then sets "LIMIT limit[0],limit[1]" statement for the model, or else it sets "LIMIT limit[0]"
// statement.
func (dao *TagDao) Limit(limit ...int) *TagDao {
	return &TagDao{M:dao.M.Limit(limit...)}
}

// Offset sets the "OFFSET" statement for the model.
// It only makes sense for some databases like SQLServer, PostgreSQL, etc.
func (dao *TagDao) Offset(offset int) *TagDao {
	return &TagDao{M:dao.M.Offset(offset)}
}

// Page sets the paging number for the model.
// The parameter <page> is started from 1 for paging.
// Note that, it differs that the Limit function start from 0 for "LIMIT" statement.
func (dao *TagDao) Page(page, limit int) *TagDao {
	return &TagDao{M:dao.M.Page(page, limit)}
}

// Batch sets the batch operation number for the model.
func (dao *TagDao) Batch(batch int) *TagDao {
	return &TagDao{M:dao.M.Batch(batch)}
}

// Cache sets the cache feature for the model. It caches the result of the sql, which means
// if there's another same sql request, it just reads and returns the result from cache, it
// but not committed and executed into the database.
//
// If the parameter <duration> < 0, which means it clear the cache with given <name>.
// If the parameter <duration> = 0, which means it never expires.
// If the parameter <duration> > 0, which means it expires after <duration>.
//
// The optional parameter <name> is used to bind a name to the cache, which means you can later
// control the cache like changing the <duration> or clearing the cache with specified <name>.
//
// Note that, the cache feature is disabled if the model is operating on a transaction.
func (dao *TagDao) Cache(duration time.Duration, name ...string) *TagDao {
	return &TagDao{M:dao.M.Cache(duration, name...)}
}

// Data sets the operation data for the model.
// The parameter <data> can be type of string/map/gmap/slice/struct/*struct, etc.
// Eg:
// Data("uid=10000")
// Data("uid", 10000)
// Data(g.Map{"uid": 10000, "name":"john"})
// Data(g.Slice{g.Map{"uid": 10000, "name":"john"}, g.Map{"uid": 20000, "name":"smith"})
func (dao *TagDao) Data(data ...interface{}) *TagDao {
	return &TagDao{M:dao.M.Data(data...)}
}

// All does "SELECT FROM ..." statement for the model.
// It retrieves the records from table and returns the result as []*model.Tag.
// It returns nil if there's no record retrieved with the given conditions from table.
//
// The optional parameter <where> is the same as the parameter of M.Where function,
// see M.Where.
func (dao *TagDao) All(where ...interface{}) ([]*model.Tag, error) {
	all, err := dao.M.All(where...)
	if err != nil {
		return nil, err
	}
	var entities []*model.Tag
	if err = all.Structs(&entities); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entities, nil
}

// One retrieves one record from table and returns the result as *model.Tag.
// It returns nil if there's no record retrieved with the given conditions from table.
//
// The optional parameter <where> is the same as the parameter of M.Where function,
// see M.Where.
func (dao *TagDao) One(where ...interface{}) (*model.Tag, error) {
	one, err := dao.M.One(where...)
	if err != nil {
		return nil, err
	}
	var entity *model.Tag
	if err = one.Struct(&entity); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entity, nil
}

// FindOne retrieves and returns a single Record by M.WherePri and M.One.
// Also see M.WherePri and M.One.
func (dao *TagDao) FindOne(where ...interface{}) (*model.Tag, error) {
	one, err := dao.M.FindOne(where...)
	if err != nil {
		return nil, err
	}
	var entity *model.Tag
	if err = one.Struct(&entity); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entity, nil
}

// FindAll retrieves and returns Result by by M.WherePri and M.All.
// Also see M.WherePri and M.All.
func (dao *TagDao) FindAll(where ...interface{}) ([]*model.Tag, error) {
	all, err := dao.M.FindAll(where...)
	if err != nil {
		return nil, err
	}
	var entities []*model.Tag
	if err = all.Structs(&entities); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entities, nil
}

// Chunk iterates the table with given size and callback function.
func (dao *TagDao) Chunk(limit int, callback func(entities []*model.Tag, err error) bool) {
	dao.M.Chunk(limit, func(result gdb.Result, err error) bool {
		var entities []*model.Tag
		err = result.Structs(&entities)
		if err == sql.ErrNoRows {
			return false
		}
		return callback(entities, err)
	})
}

// LockUpdate sets the lock for update for current operation.
func (dao *TagDao) LockUpdate() *TagDao {
	return &TagDao{M:dao.M.LockUpdate()}
}

// LockShared sets the lock in share mode for current operation.
func (dao *TagDao) LockShared() *TagDao {
	return &TagDao{M:dao.M.LockShared()}
}

// Unscoped enables/disables the soft deleting feature.
func (dao *TagDao) Unscoped() *TagDao {
	return &TagDao{M:dao.M.Unscoped()}
}