// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"database/sql"
	"focus/app/model"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
	"time"
)

// UserAuthDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type UserAuthDao struct {
	gmvc.M
	Table   string
	Columns userAuthColumns
}

// UserAuthColumns defines and stores column names for table gf_user_auth.
type userAuthColumns struct {
	Id            string // UID                      
    UserId        string // 用户ID                   
    IdentityType  string // 第三方登录类型           
    Identifier    string // 第三方登录的唯一标识     
    Credential    string // 第三方登录token或者密钥  
    CreatedAt     string // 创建时间                 
    UpdatedAt     string // 更新时间
}

var (
	// UserAuth is globally public accessible object for table gf_user_auth operations.
	UserAuth = &UserAuthDao{
		M:     g.DB("default").Table("gf_user_auth").Safe(),
		Table: "gf_user_auth",
		Columns: userAuthColumns{
			Id:           "id",             
            UserId:       "user_id",        
            IdentityType: "identity_type",  
            Identifier:   "identifier",     
            Credential:   "credential",     
            CreatedAt:    "created_at",     
            UpdatedAt:    "updated_at",
		},
	}
)

// As sets an alias name for current table.
func (d *UserAuthDao) As(as string) *UserAuthDao {
	return &UserAuthDao{M:d.M.As(as)}
}

// TX sets the transaction for current operation.
func (d *UserAuthDao) TX(tx *gdb.TX) *UserAuthDao {
	return &UserAuthDao{M:d.M.TX(tx)}
}

// Master marks the following operation on master node.
func (d *UserAuthDao) Master() *UserAuthDao {
	return &UserAuthDao{M:d.M.Master()}
}

// Slave marks the following operation on slave node.
// Note that it makes sense only if there's any slave node configured.
func (d *UserAuthDao) Slave() *UserAuthDao {
	return &UserAuthDao{M:d.M.Slave()}
}

// LeftJoin does "LEFT JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").LeftJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").LeftJoin("user_detail", "ud", "ud.uid=u.uid")
func (d *UserAuthDao) LeftJoin(table ...string) *UserAuthDao {
	return &UserAuthDao{M:d.M.LeftJoin(table...)}
}

// RightJoin does "RIGHT JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").RightJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").RightJoin("user_detail", "ud", "ud.uid=u.uid")
func (d *UserAuthDao) RightJoin(table ...string) *UserAuthDao {
	return &UserAuthDao{M:d.M.RightJoin(table...)}
}

// InnerJoin does "INNER JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").InnerJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").InnerJoin("user_detail", "ud", "ud.uid=u.uid")
func (d *UserAuthDao) InnerJoin(table ...string) *UserAuthDao {
	return &UserAuthDao{M:d.M.InnerJoin(table...)}
}

// Fields sets the operation fields of the model, multiple fields joined using char ','.
func (d *UserAuthDao) Fields(fields ...string) *UserAuthDao {
	return &UserAuthDao{M:d.M.Fields(fields...)}
}

// FieldsEx sets the excluded operation fields of the model, multiple fields joined using char ','.
func (d *UserAuthDao) FieldsEx(fields ...string) *UserAuthDao {
	return &UserAuthDao{M:d.M.FieldsEx(fields...)}
}

// Option sets the extra operation option for the model.
func (d *UserAuthDao) Option(option int) *UserAuthDao {
	return &UserAuthDao{M:d.M.Option(option)}
}

// OmitEmpty sets OPTION_OMITEMPTY option for the model, which automatically filers
// the data and where attributes for empty values.
func (d *UserAuthDao) OmitEmpty() *UserAuthDao {
	return &UserAuthDao{M:d.M.OmitEmpty()}
}

// Filter marks filtering the fields which does not exist in the fields of the operated table.
func (d *UserAuthDao) Filter() *UserAuthDao {
	return &UserAuthDao{M:d.M.Filter()}
}

// Where sets the condition statement for the model. The parameter <where> can be type of
// string/map/gmap/slice/struct/*struct, etc. Note that, if it's called more than one times,
// multiple conditions will be joined into where statement using "AND".
// Eg:
// Where("uid=10000")
// Where("uid", 10000)
// Where("money>? AND name like ?", 99999, "vip_%")
// Where("uid", 1).Where("name", "john")
// Where("status IN (?)", g.Slice{1,2,3})
// Where("age IN(?,?)", 18, 50)
// Where(User{ Id : 1, UserName : "john"})
func (d *UserAuthDao) Where(where interface{}, args ...interface{}) *UserAuthDao {
	return &UserAuthDao{M:d.M.Where(where, args...)}
}

// WherePri does the same logic as M.Where except that if the parameter <where>
// is a single condition like int/string/float/slice, it treats the condition as the primary
// key value. That is, if primary key is "id" and given <where> parameter as "123", the
// WherePri function treats the condition as "id=123", but M.Where treats the condition
// as string "123".
func (d *UserAuthDao) WherePri(where interface{}, args ...interface{}) *UserAuthDao {
	return &UserAuthDao{M:d.M.WherePri(where, args...)}
}

// And adds "AND" condition to the where statement.
func (d *UserAuthDao) And(where interface{}, args ...interface{}) *UserAuthDao {
	return &UserAuthDao{M:d.M.And(where, args...)}
}

// Or adds "OR" condition to the where statement.
func (d *UserAuthDao) Or(where interface{}, args ...interface{}) *UserAuthDao {
	return &UserAuthDao{M:d.M.Or(where, args...)}
}

// Group sets the "GROUP BY" statement for the model.
func (d *UserAuthDao) Group(groupBy string) *UserAuthDao {
	return &UserAuthDao{M:d.M.Group(groupBy)}
}

// Order sets the "ORDER BY" statement for the model.
func (d *UserAuthDao) Order(orderBy ...string) *UserAuthDao {
	return &UserAuthDao{M:d.M.Order(orderBy...)}
}

// Limit sets the "LIMIT" statement for the model.
// The parameter <limit> can be either one or two number, if passed two number is passed,
// it then sets "LIMIT limit[0],limit[1]" statement for the model, or else it sets "LIMIT limit[0]"
// statement.
func (d *UserAuthDao) Limit(limit ...int) *UserAuthDao {
	return &UserAuthDao{M:d.M.Limit(limit...)}
}

// Offset sets the "OFFSET" statement for the model.
// It only makes sense for some databases like SQLServer, PostgreSQL, etc.
func (d *UserAuthDao) Offset(offset int) *UserAuthDao {
	return &UserAuthDao{M:d.M.Offset(offset)}
}

// Page sets the paging number for the model.
// The parameter <page> is started from 1 for paging.
// Note that, it differs that the Limit function start from 0 for "LIMIT" statement.
func (d *UserAuthDao) Page(page, limit int) *UserAuthDao {
	return &UserAuthDao{M:d.M.Page(page, limit)}
}

// Batch sets the batch operation number for the model.
func (d *UserAuthDao) Batch(batch int) *UserAuthDao {
	return &UserAuthDao{M:d.M.Batch(batch)}
}

// Cache sets the cache feature for the model. It caches the result of the sql, which means
// if there's another same sql request, it just reads and returns the result from cache, it
// but not committed and executed into the database.
//
// If the parameter <duration> < 0, which means it clear the cache with given <name>.
// If the parameter <duration> = 0, which means it never expires.
// If the parameter <duration> > 0, which means it expires after <duration>.
//
// The optional parameter <name> is used to bind a name to the cache, which means you can later
// control the cache like changing the <duration> or clearing the cache with specified <name>.
//
// Note that, the cache feature is disabled if the model is operating on a transaction.
func (d *UserAuthDao) Cache(duration time.Duration, name ...string) *UserAuthDao {
	return &UserAuthDao{M:d.M.Cache(duration, name...)}
}

// Data sets the operation data for the model.
// The parameter <data> can be type of string/map/gmap/slice/struct/*struct, etc.
// Eg:
// Data("uid=10000")
// Data("uid", 10000)
// Data(g.Map{"uid": 10000, "name":"john"})
// Data(g.Slice{g.Map{"uid": 10000, "name":"john"}, g.Map{"uid": 20000, "name":"smith"})
func (d *UserAuthDao) Data(data ...interface{}) *UserAuthDao {
	return &UserAuthDao{M:d.M.Data(data...)}
}

// All does "SELECT FROM ..." statement for the model.
// It retrieves the records from table and returns the result as []*model.UserAuth.
// It returns nil if there's no record retrieved with the given conditions from table.
//
// The optional parameter <where> is the same as the parameter of M.Where function,
// see M.Where.
func (d *UserAuthDao) All(where ...interface{}) ([]*model.UserAuth, error) {
	all, err := d.M.All(where...)
	if err != nil {
		return nil, err
	}
	var entities []*model.UserAuth
	if err = all.Structs(&entities); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entities, nil
}

// One retrieves one record from table and returns the result as *model.UserAuth.
// It returns nil if there's no record retrieved with the given conditions from table.
//
// The optional parameter <where> is the same as the parameter of M.Where function,
// see M.Where.
func (d *UserAuthDao) One(where ...interface{}) (*model.UserAuth, error) {
	one, err := d.M.One(where...)
	if err != nil {
		return nil, err
	}
	var entity *model.UserAuth
	if err = one.Struct(&entity); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entity, nil
}

// FindOne retrieves and returns a single Record by M.WherePri and M.One.
// Also see M.WherePri and M.One.
func (d *UserAuthDao) FindOne(where ...interface{}) (*model.UserAuth, error) {
	one, err := d.M.FindOne(where...)
	if err != nil {
		return nil, err
	}
	var entity *model.UserAuth
	if err = one.Struct(&entity); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entity, nil
}

// FindAll retrieves and returns Result by by M.WherePri and M.All.
// Also see M.WherePri and M.All.
func (d *UserAuthDao) FindAll(where ...interface{}) ([]*model.UserAuth, error) {
	all, err := d.M.FindAll(where...)
	if err != nil {
		return nil, err
	}
	var entities []*model.UserAuth
	if err = all.Structs(&entities); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entities, nil
}

// Chunk iterates the table with given size and callback function.
func (d *UserAuthDao) Chunk(limit int, callback func(entities []*model.UserAuth, err error) bool) {
	d.M.Chunk(limit, func(result gdb.Result, err error) bool {
		var entities []*model.UserAuth
		err = result.Structs(&entities)
		if err == sql.ErrNoRows {
			return false
		}
		return callback(entities, err)
	})
}

// LockUpdate sets the lock for update for current operation.
func (d *UserAuthDao) LockUpdate() *UserAuthDao {
	return &UserAuthDao{M:d.M.LockUpdate()}
}

// LockShared sets the lock in share mode for current operation.
func (d *UserAuthDao) LockShared() *UserAuthDao {
	return &UserAuthDao{M:d.M.LockShared()}
}

// Unscoped enables/disables the soft deleting feature.
func (d *UserAuthDao) Unscoped() *UserAuthDao {
	return &UserAuthDao{M:d.M.Unscoped()}
}